### ISSUE TITLE
how to specify regex endpoints?

### ISSUE THREAD

**Issue by horacimacias** [friendsofgo/killgrave#53]
I'm trying to configure an endpoint that handles requests matching a regex.
Is there a sample configuration using this feature?

**Comment by aperezg** [comment]
Could you put an example of that you're looking for? To prepare a proper example :D?

**Comment by horacimacias** [comment]
thanks; I believe I found a way, perhaps you can confirm if this is correct.

If I understood correctly, gorilla is being used for routing, which already describes using parameters in the URLs (https://github.com/gorilla/mux#examples)
In my case, I wanted something like "/api/v1/customers/{any_customer_id}" to return the same json file.

Something like this did the trick

```json
  {
    "request": {
      "method": "GET",
      "endpoint": "/api/v1/customers/{customer_id}"
    },
    "response": {
      "status": 200,
      "headers": {
        "Content-Type": "application/json"
      },
      "bodyFile": "samplecustomer.json"
    }
  }
```

According to gorilla:

```They are defined using the format {name} or {name:pattern}. If a regular expression pattern is not defined, the matched variable will be anything until the next slash.```

**Comment by aperezg** [comment]
Yes, we're using [gorilla mux](https://github.com/gorilla/mux) for the regex, in the `urls` and the `query params`, for that reason you'll need to use his structure, in your case should be something like:

```
  {
    "request": {
      "method": "GET",
      "endpoint": "/api/v1/customers/{customer_id:[0-9]+}"
    },
    "response": {
      "status": 200,
      "headers": {
        "Content-Type": "application/json"
      },
      "bodyFile": "samplecustomer.json"
    }
  }
```

As you put, you need to declare a variable in the first step and then a pattern that is your regex. `{name:pattern}`.

For more information in the creation of the endpoints you could check the issue: https://github.com/friendsofgo/killgrave/issues/51 because for now the documentation is a little poor, but in a future we hope to have a web with all the documentation.

anything that you need, feel free to ask :)

**Comment by horacimacias** [comment]
awesome, thanks for the fast response!
